export const APP_ROUTES = {
  root: "/",
  dashboard: "/dashboard",
  events: "/events",
  calendar: "/calendar",
  settings: "/settings",
  team: "/team",
  analytics: "/analytics",
  help: "/help",
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    forgotPassword: "/auth/forgot-password",
    twoFactorRoute: "/auth/2fa/:twoFaToken",
    twoFactor: (twoFaToken: string) => `/auth/2fa/${twoFaToken}`,
    base: "/auth",
  },
  eventWizard: {
    createBase: "/organizer/events/name",
    slugs: {
      name: "name",
      description: "description",
      themeColor: "theme-color",
      paymentAccount: "payment-account",
      timeZone: "time-zone",
      venue: "venue",
      sessions: "sessions",
      discountCoupon: "discount-coupon",
      questions: "questions",
      thankYouEmail: "thank-you-email",
      advancedSettings: "advanced-settings",
      review: "review",
    },
    edit: (eventId: string) => `/organizer/events/${eventId}`,
    editStep: (eventId: string, step: string) => `/organizer/events/${eventId}/${step}`,
  },
  sessionWizard: {
    edit: (sessionId: string) => `/organizer/sessions/${sessionId}`,
    editStep: (sessionId: string, step: string) => `/organizer/sessions/${sessionId}/${step}`,
    slugs: {
      name: "name",
      description: "description",
      venue: "venue",
      event: "event",
      booking: "booking",
      startEnd: "start-end",
      schedule: "schedule",
      ticket: "ticket",
      review: "review",
    },
  },
} as const

export const API_ROUTES = {
  events: "/events",
  eventById: (id: string) => `/events/${id}`,
  eventWizardProgress: (id: string) => `/api/organizer/events/${id}/wizard-progress`,
  eventWizardNameCreate: "/api/organizer/events/name",
  eventWizardSkip: (id: string) => `/api/organizer/events/${id}/skip`,
  eventWizardStep: (id: string, step: string) => `/api/organizer/events/${id}/${step}`,
  eventWizardName: (id: string) => `/api/organizer/events/${id}/name`,
  eventWizardSessions: (id: string) => `/api/organizer/events/${id}/sessions`,
  organizerEvents: "/api/organizer/events/list",
  sessionWizardName: (id: string) => `/api/organizer/sessions/${id}/name`,
  sessionWizardDescription: (id: string) => `/api/organizer/sessions/${id}/description`,
  sessionWizardEvent: (id: string) => `/api/organizer/sessions/${id}/event`,
  sessionWizardVenue: (id: string) => `/api/organizer/sessions/${id}/venue`,
  sessionWizardProgress: (id: string) => `/api/organizer/sessions/${id}/wizard-progress`,
  organizerVenues: "/api/organizer/venues/list",
  organizerVenueCreate: "/api/organizer/venues/create",
} as const

export const API_AUTH_ROUTES = {
  authenticate: "/api/identity/account/authenticate",
  authenticateExternal: "/api/identity/account/authenticate/external-login",
  twoFactorPrefix: "/api/identity/account/2fa/",
  forgotPassword: "/api/identity/account/forgot-password",
  resetPassword: "/api/identity/account/reset-password",
  passwordVerifyLink: "/api/identity/account/password-verify-link",
  logout: "/api/identity/account/logout",
  refreshToken: "/api/identity/account/refresh-token",
  session: "/api/identity/account/session",
} as const
