export const APP_ROUTES = {
  root: "/",
  dashboard: "/dashboard",
  events: "/events",
  calendar: "/calendar",
  settings: "/organizer/payment-processor-fee/list",
  member: {
    dashboard: "/member/dashboard",
  },
  chargeRules: {
    list: "/organizer/charge-rule/list",
  },
  adminRevenuePlans: "/admin/revenue-plans/list",
  adminFeePlans: "/admin/revenue-plans/list",
  adminFeePlansLegacy: "/admin/admin-revenue-plans/list",
  adminRateLimit: "/admin/rate-limit",
  team: "/team",
  analytics: "/analytics",
  help: "/help",
  seatingLayouts: {
    list: "/organizer/seatsio/seating-layouts",
    create: "/organizer/seatsio/seating-layouts/new",
    edit: (chartUniqueId: string) => `/organizer/seatsio/seating-layouts/${chartUniqueId}`,
  },
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    forgotPassword: "/auth/forgot-password",
    twoFactorRoute: "/auth/2fa/:twoFaToken",
    twoFactor: (twoFaToken: string) => `/auth/2fa/${twoFaToken}`,
    base: "/auth",
  },
  eventWizard: {
    createBase: "/organizer/events/name",
    slugs: {
      name: "name",
      description: "description",
      termsConditions: "terms-conditions",
      banner: "banner",
      themeColor: "theme-color",
      paymentAccount: "payment-account",
      timeZone: "time-zone",
      venue: "venue",
      sessions: "sessions",
      dateTime: "date-time",
      discountCoupon: "discount-coupon",
      questions: "questions",
      thankYouEmail: "thank-you-email",
      advancedSettings: "advanced-settings",
      review: "review",
    },
    edit: (eventId: string) => `/organizer/events/${eventId}`,
    editStep: (eventId: string, step: string) => `/organizer/events/${eventId}/${step}`,
  },
  eventRegisterRoute: "/events/:eventUniqueId/register",
  eventRegister: (eventUniqueId: string) => `/events/${eventUniqueId}/register`,
  eventRegisterBootstrap: (eventUniqueId: string) => `/api/events/${eventUniqueId}/register/bootstrap`,
  eventRegisterDescription: (eventUniqueId: string) => `/api/events/${eventUniqueId}/register/description`,
  eventRegisterSessions: (eventUniqueId: string) => `/api/events/${eventUniqueId}/register/sessions`,
  eventRegisterAttendeeInfo: (eventUniqueId: string) => `/api/events/${eventUniqueId}/register/attendee-info`,
  eventRegisterQuestionnaire: (eventUniqueId: string) => `/api/events/${eventUniqueId}/register/questionnaire`,
  eventTicketViewRoute: "/events/tickets/:ticketUniqueId/view",
  eventTicketView: (ticketUniqueId: string) => `/events/tickets/${ticketUniqueId}/view`,
  eventOrderRoute: "/events/orders/:orderUniqueId",
  eventOrder: (orderUniqueId: string) => `/events/orders/${orderUniqueId}`,
  sessionWizard: {
    list: "/organizer/sessions",
    edit: (sessionId: string) => `/organizer/sessions/${sessionId}`,
    editStep: (sessionId: string, step: string) => {
      const normalizedStep = step === "booking" || step === "start-end" ? "dates-time" : step
      return `/organizer/sessions/${sessionId}/${normalizedStep}`
    },
    slugs: {
      name: "name",
      description: "description",
      banner: "banner",
      genre: "genre",
      venue: "venue",
      membershipAccess: "membership-access",
      seatSelection: "seat-selection",
      datesTime: "dates-time",
      event: "event",
      booking: "booking",
      startEnd: "start-end",
      dateTime: "dates-time",
      schedule: "schedule",
      ticket: "ticket",
      eTicketing: "e-ticketing",
      review: "review",
    },
  },
  venues: {
    list: "/organizer/venues/manage/list",
  },
  customLists: {
    base: "/organizer/membership/custom-list",
    list: "/organizer/membership/custom-list/list",
    create: "/organizer/membership/custom-list/new",
    editRoute: "/organizer/membership/custom-list/:uniqueId",
    edit: (uniqueId: string) => `/organizer/membership/custom-list/${uniqueId}`,
  },
  memberAlerts: {
    base: "/organizer/membership/alert",
    list: "/organizer/membership/alert/list",
    create: "/organizer/membership/alert/new",
    detailRoute: "/organizer/membership/alert/:uniqueId",
    detail: (uniqueId: string) => `/organizer/membership/alert/${uniqueId}`,
    editRoute: "/organizer/membership/alert/:uniqueId/edit",
    edit: (uniqueId: string) => `/organizer/membership/alert/${uniqueId}/edit`,
  },
  documentCategories: {
    base: "/organizer/membership/document-category",
    list: "/organizer/membership/document-category/list",
    create: "/organizer/membership/document-category/new",
    detailRoute: "/organizer/membership/document-category/:uniqueId",
    detail: (uniqueId: string) => `/organizer/membership/document-category/${uniqueId}`,
    editRoute: "/organizer/membership/document-category/:uniqueId/edit",
    edit: (uniqueId: string) => `/organizer/membership/document-category/${uniqueId}/edit`,
  },
  memberDocuments: {
    base: "/member-documents",
    list: "/member-documents/categories",
    detailRoute: "/member-documents/categories/:uniqueId",
    detail: (uniqueId: string) => `/member-documents/categories/${uniqueId}`,
  },
  alertInbox: "/alerts",
  alertInboxDetailRoute: "/alerts/:recipientUniqueId",
  alertInboxDetail: (recipientUniqueId: string) => `/alerts/${recipientUniqueId}`,
  eventInvoices: {
    list: "/organizer/events/invoices",
    listForEvent: (eventUniqueId: string) =>
      `/organizer/events/invoices?eventUniqueId=${encodeURIComponent(eventUniqueId)}`,
    detailRoute: "/organizer/events/invoices/:invoiceUniqueId",
    detail: (invoiceUniqueId: string) => `/organizer/events/invoices/${invoiceUniqueId}`,
  },
} as const

export const API_ROUTES = {
  events: "/events",
  eventById: (id: string) => `/events/${id}`,
  eventRegister: (eventUniqueId: string) => `/api/events/${eventUniqueId}/register`,
  eventRegisterBootstrap: (eventUniqueId: string) => `/api/events/${eventUniqueId}/register/bootstrap`,
  eventRegisterDescription: (eventUniqueId: string) => `/api/events/${eventUniqueId}/register/description`,
  eventRegisterSessions: (eventUniqueId: string) => `/api/events/${eventUniqueId}/register/sessions`,
  eventRegisterAttendeeInfo: (eventUniqueId: string) => `/api/events/${eventUniqueId}/register/attendee-info`,
  eventRegisterQuestionnaire: (eventUniqueId: string) => `/api/events/${eventUniqueId}/register/questionnaire`,
  eventCart: "/api/events/cart",
  eventCartDetail: (cartUniqueId: string) => `/api/events/cart/${cartUniqueId}`,
  eventCartLines: (cartUniqueId: string) => `/api/events/cart/${cartUniqueId}/lines`,
  eventCartLine: (cartUniqueId: string, lineUniqueId: string) =>
    `/api/events/cart/${cartUniqueId}/lines/${lineUniqueId}`,
  eventCartPrice: (cartUniqueId: string) => `/api/events/cart/${cartUniqueId}/price`,
  eventCartLineAttendees: (cartUniqueId: string, lineUniqueId: string) =>
    `/api/events/cart/${cartUniqueId}/lines/${lineUniqueId}/attendees`,
  eventCartAnswers: (cartUniqueId: string) => `/api/events/cart/${cartUniqueId}/answers`,
  eventCartAnswerFiles: (cartUniqueId: string) => `/api/events/cart/${cartUniqueId}/answers/files`,
  eventCartCheckoutIntent: (cartUniqueId: string) => `/api/events/cart/${cartUniqueId}/checkout/intent`,
  eventCartCheckoutCheque: (cartUniqueId: string) => `/api/events/cart/${cartUniqueId}/checkout/cheque`,
  eventCartCheckoutConfirm: (cartUniqueId: string) => `/api/events/cart/${cartUniqueId}/checkout/confirm`,
  eventTicketView: (ticketUniqueId: string) => `/api/events/tickets/${ticketUniqueId}/view`,
  eventOrderStatus: (orderUniqueId: string) => `/api/events/orders/${orderUniqueId}`,
  eventWizardProgress: (id: string) => `/api/organizer/events/${id}/wizard-progress`,
  eventWizardNameCreate: "/api/organizer/events/name",
  eventWizardSkip: (id: string) => `/api/organizer/events/${id}/skip`,
  eventWizardStep: (id: string, step: string) => `/api/organizer/events/${id}/${step}`,
  eventWizardName: (id: string) => `/api/organizer/events/${id}/name`,
  eventWizardSetupStateOptions: "/api/organizer/events/setup-state/options",
  organizerEventStatusOptions: "/api/organizer/events/status-options",
  eventWizardReviewSummary: (id: string) => `/api/organizer/events/${id}/review-summary`,
  eventWizardSetupStateReview: (id: string) => `/api/organizer/events/${id}/setup-state/review`,
  eventWizardSetupState: (id: string) => `/api/organizer/events/${id}/setup-state`,
  eventWizardDateTime: (id: string) => `/api/organizer/events/${id}/date-time`,
  eventWizardDateTimeAutofill: (id: string) => `/api/organizer/events/${id}/date-time/autofill`,
  eventWizardVisibilityOptions: "/api/organizer/events/visibility/options",
  eventWizardPurchaseTimeLimitOptions: "/api/organizer/events/purchase-time-limit/options",
  eventEmailTemplatePlaceHolders: "/api/organizer/events/email-template/place-holders",
  eventEmailTemplateSnippetCreate: "/api/organizer/events/email-template/snippet/create",
  eventEmailTemplateSnippetList: "/api/organizer/events/email-template/snippet/list",
  eventEmailTemplateSnippetDetail: (snippetId: string) => `/api/organizer/events/email-template/snippet/${snippetId}/detail`,
  eventEmailTemplateSnippetUpdate: (snippetId: string) => `/api/organizer/events/email-template/snippet/${snippetId}/update`,
  eventEmailTemplateSnippetDelete: (snippetId: string) => `/api/organizer/events/email-template/snippet/${snippetId}/delete`,
  eventWizardSessions: (id: string) => `/api/organizer/events/${id}/sessions`,
  eventWizardDiscountCoupon: (id: string) => `/api/organizer/events/${id}/discount-coupon`,
  eventWizardQuestions: (id: string) => `/api/organizer/events/${id}/questions`,
  organizerPaymentMerchantMethods: (paymentMerchantId: number) =>
    `/api/organizer/payment-merchant/${paymentMerchantId}/payment-methods`,
  organizerPaymentProcessorFees: "/api/organizer/payment-processor-fee/list",
  organizerPaymentProcessorFeeCreate: "/api/organizer/payment-processor-fee/create",
  organizerPaymentProcessorFeeUpdate: (paymentProcessorFeeId: string) =>
    `/api/organizer/payment-processor-fee/${paymentProcessorFeeId}/update`,
  organizerChargeRules: "/api/organizer/charge-rule/list",
  organizerChargeRuleCreate: "/api/organizer/charge-rule/create",
  organizerChargeRuleUpdate: (chargeRuleId: string) => `/api/organizer/charge-rule/${chargeRuleId}/update`,
  adminRevenuePlans: "/api/admin/revenue-plans/list",
  adminFeePlans: "/api/admin/revenue-plans/list",
  adminRateLimit: "/api/admin/rate-limit",
  adminRevenuePlanDetail: (uniqueId: string) => `/api/admin/revenue-plans/${uniqueId}/detail`,
  adminRevenuePlanOrganizers: (uniqueId: string) => `/api/admin/revenue-plans/${uniqueId}/organizers`,
  adminRevenuePlanCreate: "/api/admin/revenue-plans/create",
  adminRevenuePlanUpdate: (uniqueId: string) => `/api/admin/revenue-plans/${uniqueId}/update`,
  adminRevenuePlanModuleSave: (uniqueId: string) => `/api/admin/revenue-plans/${uniqueId}/modules`,
  adminRevenuePlanMetadataUpdate: (uniqueId: string) => `/api/admin/revenue-plans/${uniqueId}/metadata`,
  adminRevenuePlanAssignOrganizers: (uniqueId: string) => `/api/admin/revenue-plans/${uniqueId}/map`,
  adminRevenuePlanUnassignOrganizer: (uniqueId: string, organizerUniqueId: string) =>
    `/api/admin/revenue-plans/${uniqueId}/unmap/${organizerUniqueId}`,
  adminRevenuePlanUnmapModule: (uniqueId: string, moduleId: number) => `/api/admin/revenue-plans/${uniqueId}/modules/${moduleId}`,
  adminRevenuePlanModules: "/api/admin/revenue-plans/modules",
  adminRevenuePlanScopes: "/api/admin/list-items/revenue-plan-scopes",
  adminOrganizersList: "/api/admin/organizer/list/Active",
  adminTimeZones: "/api/admin/list-items/time-zones",
  adminPaymentMerchants: "/api/admin/list-items/payment-merchants",
  organizerEvents: "/api/organizer/events/list",
  membershipTypeOptions: "/api/organizer/membership/type/options",
  membershipStatusOptions: "/api/organizer/membership/type/status-options",
  seatsIoWorkspace: "/api/organizer/seatsio/workspace",
  seatsIoSeatingLayouts: "/api/organizer/seatsio/seating-layouts",
  seatsIoSeatingLayout: (chartUniqueId: string) => `/api/organizer/seatsio/seating-layouts/${chartUniqueId}`,
  seatsIoChartValidation: (chartKey: string) =>
    `/api/organizer/seatsio/seating-layouts/${encodeURIComponent(chartKey)}/validation`,
  seatsIoVenueCharts: (venueUniqueId: string) => `/api/organizer/seatsio/venues/${venueUniqueId}/charts`,
  seatsIoChartCategories: (chartUniqueId: string) => `/api/organizer/seatsio/seating-layouts/${chartUniqueId}/categories`,
  seatsIoChartEvents: (chartUniqueId: string) => `/api/organizer/seatsio/seating-layouts/${chartUniqueId}/events`,
  seatsIoChartCategory: (chartUniqueId: string, categoryUniqueId: string) =>
    `/api/organizer/seatsio/seating-layouts/${chartUniqueId}/categories/${categoryUniqueId}`,
  sessionWizardName: (id: string) => `/api/organizer/sessions/${id}/name`,
  sessionWizardDescription: (id: string) => `/api/organizer/sessions/${id}/description`,
  sessionWizardBanner: (id: string) => `/api/organizer/sessions/${id}/banner`,
  sessionWizardGenre: (id: string) => `/api/organizer/sessions/${id}/genre`,
  sessionWizardGenreCreate: (id: string) => `/api/organizer/sessions/${id}/genre/create`,
  sessionWizardSkip: (id: string) => `/api/organizer/sessions/${id}/skip`,
  sessionWizardEvent: (id: string) => `/api/organizer/sessions/${id}/event`,
  sessionWizardVenue: (id: string) => `/api/organizer/sessions/${id}/venue`,
  sessionWizardMembershipAccess: (id: string) => `/api/organizer/sessions/${id}/membership-access`,
  sessionWizardSeatSelection: (id: string) => `/api/organizer/sessions/${id}/seat-selection`,
  sessionWizardDateTime: (id: string) => `/api/organizer/sessions/${id}/dates-time`,
  sessionWizardBooking: (id: string) => `/api/organizer/sessions/${id}/booking`,
  sessionWizardDuration: (id: string) => `/api/organizer/sessions/${id}/start-end`,
  sessionWizardSchedule: (id: string) => `/api/organizer/sessions/${id}/schedule`,
  sessionWizardScheduleItem: (id: string, scheduleId: string) =>
    `/api/organizer/sessions/${id}/schedule/${scheduleId}`,
  sessionWizardTicket: (id: string) => `/api/organizer/sessions/${id}/ticket`,
  sessionWizardTicketItem: (id: string, ticketId: string) => `/api/organizer/sessions/${id}/ticket/${ticketId}`,
  sessionWizardTicketDisplayOrder: (id: string) => `/api/organizer/sessions/${id}/ticket/display-order`,
  sessionWizardTicketPricePeriod: (id: string, ticketId: string) =>
    `/api/organizer/sessions/${id}/ticket/${ticketId}/price-period`,
  sessionWizardTicketPricePeriodItem: (id: string, ticketId: string, pricePeriodId: string) =>
    `/api/organizer/sessions/${id}/ticket/${ticketId}/price-period/${pricePeriodId}`,
  sessionWizardSetupStateOptions: "/api/organizer/sessions/setup-state/options",
  sessionWizardReviewSummary: (id: string) => `/api/organizer/sessions/${id}/review-summary`,
  sessionWizardSetupStateReview: (id: string) => `/api/organizer/sessions/${id}/setup-state/review`,
  sessionWizardSetupState: (id: string) => `/api/organizer/sessions/${id}/setup-state`,
  sessionWizardETicketing: (id: string) => `/api/organizer/sessions/${id}/e-ticketing`,
  sessionWizardProgress: (id: string) => `/api/organizer/sessions/${id}/wizard-progress`,
  sessionSeatsIoEvent: (id: string) => `/api/organizer/sessions/${id}/seatsio/event`,
  sessionsList: "/api/organizer/sessions/list",
  sessionsFilterOptions: "/api/organizer/sessions/filter-options",
  organizerVenues: "/api/organizer/venues/list",
  organizerVenueCreate: "/api/organizer/venues/create",
  organizerVenueManagementList: "/api/organizer/venues/manage/list",
  organizerVenueUpdate: (uniqueId: string) => `/api/organizer/venues/${uniqueId}/update`,
  organizerCustomFormControls: "/api/organizer/custom-form/controls",
  organizerCustomFormListItems: "/api/organizer/custom-form/list-items",
  organizerCustomFormPreview: (id: string) => `/api/organizer/custom-form/${id}/edit`,
  customLists: "/api/organizer/membership/custom-list/list",
  customListOptions: "/api/organizer/membership/custom-list/options",
  customListMembershipTypeOptions: "/api/organizer/membership/custom-list/membership-type-options",
  customListMemberOptions: "/api/organizer/membership/custom-list/member-options",
  customListCreate: "/api/organizer/membership/custom-list",
  customListDetail: (uniqueId: string) => `/api/organizer/membership/custom-list/${uniqueId}`,
  customListUpdate: (uniqueId: string) => `/api/organizer/membership/custom-list/${uniqueId}`,
  customListDelete: (uniqueId: string) => `/api/organizer/membership/custom-list/${uniqueId}`,
  customListMembers: (uniqueId: string) => `/api/organizer/membership/custom-list/${uniqueId}/members`,

  memberAlerts: "/api/organizer/membership/alert/list",
  memberAlertDetail: (uniqueId: string) => `/api/organizer/membership/alert/${uniqueId}`,
  memberAlertRecipients: (uniqueId: string) => `/api/organizer/membership/alert/${uniqueId}/recipients`,
  memberAlertRecipientOptions: "/api/organizer/membership/alert/recipient-options",
  memberAlertMembershipTypeOptions: "/api/organizer/membership/alert/membership-type-options",
  memberAlertCustomListOptions: "/api/organizer/membership/alert/custom-list-options",
  memberAlertCustomListPreview: "/api/organizer/membership/alert/custom-list-preview",
  memberAlertCreate: "/api/organizer/membership/alert",
  memberAlertResend: (uniqueId: string) => `/api/organizer/membership/alert/${uniqueId}/resend`,
  memberAlertDelete: (uniqueId: string) => `/api/organizer/membership/alert/${uniqueId}`,
  membershipTypeMembers: "/api/organizer/membership/type/members",

  documentCategories: "/api/organizer/membership/document-category/list",
  documentCategoryMembershipTypeOptions: "/api/organizer/membership/document-category/membership-type-options",
  documentCategoryCreate: "/api/organizer/membership/document-category",
  documentCategoryDetail: (uniqueId: string) => `/api/organizer/membership/document-category/${uniqueId}`,
  documentCategoryDocuments: (uniqueId: string) =>
    `/api/organizer/membership/document-category/${uniqueId}/documents`,
  documentCategoryDocumentDownload: (documentUniqueId: string) =>
    `/api/organizer/membership/document-category/documents/${documentUniqueId}/download`,

  memberDocumentCategories: "/api/member-documents/categories",
  memberDocumentCategoryDetail: (uniqueId: string) => `/api/member-documents/categories/${uniqueId}`,
  memberDocumentCategoryDocuments: (uniqueId: string) =>
    `/api/member-documents/categories/${uniqueId}/documents`,
  memberDocumentView: (documentUniqueId: string) =>
    `/api/member-documents/documents/${documentUniqueId}`,
  memberDocumentDownload: (documentUniqueId: string) =>
    `/api/member-documents/documents/${documentUniqueId}/download`,

  alertInbox: "/api/alert-inbox/list",
  alertInboxItem: (recipientUniqueId: string) => `/api/alert-inbox/${recipientUniqueId}`,
  alertInboxUnreadCount: "/api/alert-inbox/unread-count",
  alertInboxUnseenCount: "/api/alert-inbox/unseen-count",
  alertInboxMarkAllSeen: "/api/alert-inbox/seen",
  alertInboxClaimInstantToasts: "/api/alert-inbox/instant-toasts/claim",
  alertInboxMarkRead: (recipientUniqueId: string) => `/api/alert-inbox/${recipientUniqueId}/read`,
  eventInvoices: "/api/organizer/events/invoices/list",
  eventInvoiceFilterOptions: "/api/organizer/events/invoices/filter-options",
  eventInvoiceDetail: (invoiceUniqueId: string) => `/api/organizer/events/invoices/${invoiceUniqueId}`,
  eventInvoiceResend: (invoiceUniqueId: string) => `/api/organizer/events/invoices/${invoiceUniqueId}/resend`,
  eventInvoiceAddNote: (invoiceUniqueId: string) => `/api/organizer/events/invoices/${invoiceUniqueId}/add-note`,
  eventInvoiceBuyer: (invoiceUniqueId: string) => `/api/organizer/events/invoices/${invoiceUniqueId}/buyer`,
  eventInvoiceMarkPaid: (invoiceUniqueId: string) => `/api/organizer/events/invoices/${invoiceUniqueId}/mark-paid`,
  eventInvoiceCancel: (invoiceUniqueId: string) => `/api/organizer/events/invoices/${invoiceUniqueId}/cancel`,
  eventInvoiceTicketResend: (invoiceUniqueId: string, ticketUniqueId: string) =>
    `/api/organizer/events/invoices/${invoiceUniqueId}/tickets/${ticketUniqueId}/resend`,
  stripePublicCredentials: (paymentAccountUniqueId: string) =>
    `/api/public/stripe/${paymentAccountUniqueId}/credentials`,
} as const

export const API_AUTH_ROUTES = {
  authenticate: "/api/identity/account/authenticate",
  authenticateExternal: "/api/identity/account/authenticate/external-login",
  twoFactorPrefix: "/api/identity/account/2fa/",
  forgotPassword: "/api/identity/account/forgot-password",
  resetPassword: "/api/identity/account/reset-password",
  passwordVerifyLink: "/api/identity/account/password-verify-link",
  logout: "/api/identity/account/logout",
  refreshToken: "/api/identity/account/refresh-token",
  session: "/api/identity/account/session",
} as const
